Supporting null safety
abhishekUpmanyu/swipe_up pull request #2
Opened 2021-07-19 10:15 UTC by KarimAbdo

2021-08-05 13:41 UTC, abhishekUpmanyu commented
Hi @KarimAbdo, thanks a lot for contributing to my repo.
Can you please update the version from 1.0.0 to 1.1.0 in pubspec.yaml
Also please remove those null checking assert statements for child and body.
Everything else looks perfect! :)

2021-09-21 07:42 UTC, BK1031 commented
So when is this getting merged?

2021-09-29 23:32 UTC, bdlukaa requested changes

2021-09-29 23:32 UTC, bdlukaa commented on lib/swipe_up.dart
> +          widget.onSwipe!();
```suggestion
          widget.onSwipe?.call();
```

2021-11-09 18:11 UTC, abhishekUpmanyu commented
Sorry about the delay, merging the PR now

2021-11-09 18:11 UTC, merged